"DbUser" = "psqladminun@postgresql-challenge-01"
"DbPassword" = "OBBzSsbTSnznYMH6"
"DbName" = "challengedb"
"DbPort" = "5432"
"DbHost" = "postgresql-challenge-01.postgres.database.azure.com"
"ListenHost" = "0.0.0.0"
"ListenPort" = "3000"